// Mocks generated by Mockito 5.4.5 from annotations
// in frontend/test/domain/subscription/usecase/purchase_subscription_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/domain/core/entity/subscription_status.dart' as _i2;
import 'package:frontend/domain/core/type/subscription_type.dart' as _i5;
import 'package:frontend/domain/subscription/repository/subscription_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSubscriptionStatus_0 extends _i1.SmartFake
    implements _i2.SubscriptionStatus {
  _FakeSubscriptionStatus_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i3.SubscriptionRepository {
  MockSubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SubscriptionStatus> getSubscriptionStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionStatus,
          [],
        ),
        returnValue:
            _i4.Future<_i2.SubscriptionStatus>.value(_FakeSubscriptionStatus_0(
          this,
          Invocation.method(
            #getSubscriptionStatus,
            [],
          ),
        )),
      ) as _i4.Future<_i2.SubscriptionStatus>);

  @override
  _i4.Future<bool> purchaseSubscription(_i5.SubscriptionType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #purchaseSubscription,
          [type],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> verifySubscription() => (super.noSuchMethod(
        Invocation.method(
          #verifySubscription,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> restorePurchases() => (super.noSuchMethod(
        Invocation.method(
          #restorePurchases,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> cancelSubscription() => (super.noSuchMethod(
        Invocation.method(
          #cancelSubscription,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i5.SubscriptionType>> getAvailableSubscriptions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableSubscriptions,
          [],
        ),
        returnValue: _i4.Future<List<_i5.SubscriptionType>>.value(
            <_i5.SubscriptionType>[]),
      ) as _i4.Future<List<_i5.SubscriptionType>>);

  @override
  _i4.Future<bool> hasFeature(_i5.PremiumFeature? feature) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasFeature,
          [feature],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Stream<_i2.SubscriptionStatus> watchSubscriptionStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchSubscriptionStatus,
          [],
        ),
        returnValue: _i4.Stream<_i2.SubscriptionStatus>.empty(),
      ) as _i4.Stream<_i2.SubscriptionStatus>);

  @override
  _i4.Stream<_i3.PurchaseStatus> watchPurchaseStatus() => (super.noSuchMethod(
        Invocation.method(
          #watchPurchaseStatus,
          [],
        ),
        returnValue: _i4.Stream<_i3.PurchaseStatus>.empty(),
      ) as _i4.Stream<_i3.PurchaseStatus>);

  @override
  _i4.Future<Map<String, dynamic>?> getSubscriptionPrice(
          _i5.SubscriptionType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionPrice,
          [type],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<bool> applyPromoCode(String? promoCode) => (super.noSuchMethod(
        Invocation.method(
          #applyPromoCode,
          [promoCode],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> setAutoRenew(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setAutoRenew,
          [enabled],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i3.PurchaseHistory>> getPurchaseHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPurchaseHistory,
          [],
        ),
        returnValue: _i4.Future<List<_i3.PurchaseHistory>>.value(
            <_i3.PurchaseHistory>[]),
      ) as _i4.Future<List<_i3.PurchaseHistory>>);

  @override
  _i4.Future<Map<String, dynamic>> getSubscriptionDetails() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionDetails,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
