name: Build Base Image

on:
  push:
    tags:
      - "base-v*"

defaults:
  run:
    working-directory: "./backend/.docker/base"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  name: base

jobs:
  build:
    name: Build Base Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}
          mask-aws-account-id: true

      - name: get_caller_identify
        run: aws sts get-caller-identify

      - name: login ecr
        run: aws-actions/amazon-ecr-login@v1

      - name: get gat version
        env:
          REF: ${{ github.ref }}
        run: echo "tag_version=$(echo "${REF##*/base-v}")" >> $GITHUB_ENV